input_data: model/national_model

run:
  name: "national_test" # use this to keep track of runs with different settings
  disable_progressbar: false # set to true to disable the progressbar
  shared_resources: false # set to true to share the default resources across runs
  shared_cutouts: true # set to true to share the default cutout(s) across runs
  validation: false # set to true to run back-casting plots
  export_csv: true # set to true to export csv files of the model outputs

year_settings:
  ref_year: 2021
  start_year: 2025
  forecast_year: 2050
  investment_period: [2025, 2030, 2050]
  discount_rate: 0.05

solving:
  options:
    dispatch:
      include_objective_constant : true
      load_shedding: false
      linearized_unit_commitment: false
      keep_files: false
      store_model: false
  solver:
    name: &solver_name highs
    options: highs-fast
  solver_options:
    "highs-fast":
      threads: 8
      solver: ipm
      run_crossover: 'off'
      small_matrix_value: 1.0e-06
      large_matrix_value: 1000000000.0
      primal_feasibility_tolerance: 1.0e-01
      dual_feasibility_tolerance: 1.0e-01
      ipm_optimality_tolerance: 0.01
      parallel: 'on'
      random_seed: 123
      # time_limit: 30
      mip_abs_gap: 0.1
      mip_rel_gap: 0.1

load:
  load_mode: &load_mode "custom"
  load_growth_forecast: "model/national_model/loads_forecast.csv"

components:
  override_dir: ""
  components_dir: "data/components"
  costs_dir: "data/costs"
  obps: true
  technology_costs: "Default_costs"
  carbon_tax:
    "2021": 50 # $ per tonne, based on federal minimums
    "2025": 125
    "2030": 170

snapshots:
  method: "OPT_VRE_HYDRO"
  load_mode: *load_mode
  folder_name: "model/national_model"
  last_investment_period: 5 #duration in years

  # Rep days config
  # rep_length: None
  cluster: 5
  include_hydro: true
  solver: *solver_name
  extreme_days_select: false
  save_fig: false
  save_csv: false
  saving_folder_path: saves
  provinces_selection: ["AB", "BC", "MB", "NB", "NS", "ON", "PE", "QC", "SK", "NL"]
  # year: None
  aggregate: false

extra_loads:
  is_used: false
  extra_loads: data/base
  path: data/base

planning:
  constraints:
    add_bidirection_link:
      enable: false
    add_stop_production:
      enable: false
    CER_constraint:
      enable: false
      # aggregation levels: provincial, group, individual
      aggregation: 'provincial'
      # year that constraint becomes active
      year: 2035
      # carriers to include
      carriers: ['oil', 'gas', 'diesel']
      # values for emissions limit and offset is emission intensity (in tC02eq/GWh)
      values: {
        limit: {2035: 65, 2050: 0},
        offset: {2035: 35, 2050: 42}
        }
      # minimum capacity
      min_cap: 25
    NZ_constraint:
      enable: false
    planning_reserve_margin:
      enable: false
      capacity_values_placeholder_filepath: "data/constraints/capacity_values_placeholder.csv"
      # provinces_list:
      #   "PE": 1.2
      #   "NB": 1.2
      #   "NS": 1.2
      #   "AB": 1.2
      #   "BC": 1.2
      #   "MB": 1.2
      #   "ON": 1.2
      #   "QC": 1.2
      #   "SK": 1.2
      #   "NL": 1.2
    component_capacity_expansion_constraint:
      enable: false
      # custom_constraint_filepath: ""

dispatch:
  #Snapshots related
  horizon: 8760 #336 #2 weeks in hours
  overlap: 0 #48
  investment_period: [2025] #If empty, it will take the planning investment periods

  constraints:
    add_stop_production:
      enable: false
      2030: ["coal"]
    add_spilling_variable:
      enable: false
    add_bidirection_link:
      enable: false
    add_prevent_spill_if_not_fully_charged:
      enable: false
    #   maximum_soc_storage_value: 2000
    CER_constraint:
      enable: false
      # modes = hourly, emissions
      mode: 'emissions'
      # aggregation levels: provincial, group, individual
      aggregation: 'provincial'
      # year that constraint becomes active
      year: 2035
      # carriers to include
      carriers: ['oil', 'gas', 'diesel']
      # values for hourly mode is number of hours, values for emissions mode is emission intensity (in tC02eq/GWh)
      values: {
        limit: {2035: 65, 2050: 0},
        offset: {2035: 35, 2050: 42}
        }
      # minimum capacity
      min_cap: 25
      # forecast hours based on net load ('load'), uniformly ('uniform'), or assign max to first UC period and carry leftover ('carryover')
      forecast_hours: 'carryover'

postprocess:
  result_type: "Provincial"  # "Provincial" or "Nodal"
  reference_scenario: 0  # 0 = auto-select (scenario with most representative days)
  export_format: "idea"  # null = no export, "idea" = export to IDEA template format

